### ISSUE TITLE
Unnecessary error while loading index.html

### ISSUE THREAD

**Issue by vishal41190** [zabkaatlarge/Askr#1]
When i open index.html in browser. There are 4-5 errors in console regarding unable to load content. Looks like not proper path to script or css

**Comment by bmwatson888** [comment]
I'll check in the morning but I'm pretty sure it's correct. It might be some of the files are missing from the git sync.  The html is pretty uncomplicated so it should be easy to figure out. 

- Brian

**Comment by vishal41190** [comment]
![image](https://cloud.githubusercontent.com/assets/7388112/6519611/80561798-c36b-11e4-90cf-a9245bda4fd5.png)

**Comment by bmwatson888** [comment]
Should be good now. Just synced the changes. There were some unused css files being referenced from the bootstrap template. Should have still rendered in the browser though without those changes. 

- Brian
